CLASIFICACION BINARIA

PREPROCESAMIENTO CON PANDAS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/Obfuscated-MalMem2022 Mod 1.csv')

In [ ]:
print(df)

                                                  Benign  45  17  10.55555556  \
0                                                 Benign  47  19    11.531915   
1                                                 Benign  40  14    14.725000   
2                                                 Benign  32  13    13.500000   
3                                                 Benign  42  16    11.452381   
4                                                 Benign  40  12    13.800000   
...                                                  ...  ..  ..          ...   
58590  Ransomware-Shade-fa03be3078d1b9840f06745f160eb...  37  15    10.108108   
58591  Ransomware-Shade-f56687137caf9a67678cde91e4614...  37  14     9.945946   
58592  Ransomware-Shade-faddeea111a25da4d0888f3044ae9...  38  15     9.842105   
58593  Ransomware-Shade-f866c086af2e1d8ebaa6f2c863157...  37  15    10.243243   
58594  Ransomware-Shade-955d9af38346c1755527bd196668e...  38  15     9.868421   

       0  202.8444444  1694

SE ELIMINA LA PRIMERA COLUMNA POR INFORMACION IRRELEVANTE

In [ ]:
df = df.iloc[:, 1:]

In [ ]:
print(df)

       45  17  10.55555556  0  202.8444444  1694       38.5   9129  \
0      47  19    11.531915  0   242.234043  2074  44.127660  11385   
1      40  14    14.725000  0   288.225000  1932  48.300000  11529   
2      32  13    13.500000  0   264.281250  1445  45.156250   8457   
3      42  16    11.452381  0   281.333333  2067  49.214286  11816   
4      40  12    13.800000  0   306.950000  2082  52.050000  12278   
...    ..  ..          ... ..          ...   ...        ...    ...   
58590  37  15    10.108108  0   215.486487  1453  39.270270   7973   
58591  37  14     9.945946  0   190.216216  1347  36.405405   7038   
58592  38  15     9.842105  0   210.026316  1448  38.105263   7982   
58593  37  15    10.243243  0   215.513513  1452  39.243243   7974   
58594  38  15     9.868421  0   213.026316  1487  39.131579   8095   

       212.3023256  0.1  ...  221  26  24  116  0.4  121  87  0.5  8  Benign.1  
0       242.234043    0  ...  222  26  24  118    0  122  87    0  8    Benign

EN LA ETIQUETA OSEA Y SE REEMPLAZA BENIGN POR 1 Y MALWARE POR 0

In [ ]:
# Posición de la columna
posicion_columna = 56

# Diccionario de reemplazo
reemplazo = {'Benign': 1, 'Malware': 0}

# Cambiar valores en la columna 56
df.iloc[:, :56] = df.iloc[:, :56].replace(reemplazo)

In [ ]:
print(df)

       45  17  10.55555556  0  202.8444444  1694       38.5   9129  \
0      47  19    11.531915  0   242.234043  2074  44.127660  11385   
1      40  14    14.725000  0   288.225000  1932  48.300000  11529   
2      32  13    13.500000  0   264.281250  1445  45.156250   8457   
3      42  16    11.452381  0   281.333333  2067  49.214286  11816   
4      40  12    13.800000  0   306.950000  2082  52.050000  12278   
...    ..  ..          ... ..          ...   ...        ...    ...   
58590  37  15    10.108108  0   215.486487  1453  39.270270   7973   
58591  37  14     9.945946  0   190.216216  1347  36.405405   7038   
58592  38  15     9.842105  0   210.026316  1448  38.105263   7982   
58593  37  15    10.243243  0   215.513513  1452  39.243243   7974   
58594  38  15     9.868421  0   213.026316  1487  39.131579   8095   

       212.3023256  0.1  ...  221  26  24  116  0.4  121  87  0.5  8  Benign.1  
0       242.234043    0  ...  222  26  24  118    0  122  87    0  8         1

In [ ]:
df.to_csv('/content/drive/MyDrive/Dataset/Obfuscated-MalMem2022 Mod 2.csv')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/Obfuscated-MalMem2022 Mod 2.csv')

In [ ]:
print(df)

           0  45  17  10.55555556  0.6  202.8444444  1694       38.5   9129  \
0          0  47  19    11.531915    0   242.234043  2074  44.127660  11385   
1          1  40  14    14.725000    0   288.225000  1932  48.300000  11529   
2          2  32  13    13.500000    0   264.281250  1445  45.156250   8457   
3          3  42  16    11.452381    0   281.333333  2067  49.214286  11816   
4          4  40  12    13.800000    0   306.950000  2082  52.050000  12278   
...      ...  ..  ..          ...  ...          ...   ...        ...    ...   
58590  58590  37  15    10.108108    0   215.486487  1453  39.270270   7973   
58591  58591  37  14     9.945946    0   190.216216  1347  36.405405   7038   
58592  58592  38  15     9.842105    0   210.026316  1448  38.105263   7982   
58593  58593  37  15    10.243243    0   215.513513  1452  39.243243   7974   
58594  58594  38  15     9.868421    0   213.026316  1487  39.131579   8095   

       212.3023256  ...  221  26  24  116  0.4  121

YA QUE LOS DATOS ESTAN ORDENADO DE MANERA QUE EN EL ENTRENAMIENTO NO PERMITIRIA HACER UNA PREDICCION CORRECTA SE PENSÓ EN LA OPCION DE REORDENAR LOS EJEMPLOS DE MANERA ALEATORIA ASI QUE PARA QUE EL ENTRENAMIENTO PUEDA ALCANZAR LA MAYOR CANTIDAD DIVERSA DE EJEMPLOS

In [ ]:
df = df.sample(frac=1)

In [ ]:
print(df)

           0  45  17  10.55555556  0.6  202.8444444  1694       38.5   9129  \
30074  30074  38  15    10.052632    0   213.815789  1491  39.236842   8125   
56681  56681  45  17     9.377778    0   203.688889  1722  38.266667   9167   
29360  29360  51  21     8.529412    0   177.117647  1745  34.215686   9037   
9117    9117  41  12    12.997410    0   294.856249  2029  49.487805  12089   
51930  51930  45  18     9.111111    0   194.577778  1676  37.244444   8757   
...      ...  ..  ..          ...  ...          ...   ...        ...    ...   
55705  55705  44  16    10.113636    0   210.431818  1705  38.750000   9260   
14675  14675  40  13    13.072626    0   290.215503  2015  50.375000  11608   
38400  38400  42  16    10.071429    0   205.500000  1607  38.261905   8631   
37048  37048  39  15    11.410256    0   220.846154  1563  40.076923   8613   
44816  44816  37  15    10.162162    0   215.135135  1445  39.054054   7960   

       212.3023256  ...  221  26  24  116  0.4  121

In [ ]:
df.to_csv('/content/drive/MyDrive/Dataset/Obfuscated-MalMem2022 Mod 3.csv')

In [ ]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np

# Plotting library
from matplotlib import pyplot

# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
# from scipy.io import loadmat

# library written for this exercise providing additional functions for assignment submission, and others
# import utils


# tells matplotlib to embed plots within the notebook
%matplotlib inline

SE CARGAN LOS DATOS DEL DATASET

In [ ]:
#  datos de entrenamiento almacenados en los arreglos X, y
# data = np.loadtxt("/content/gdrive/MyDrive/Colab Notebooks/machine learning/datasets/wine_preparado.csv", delimiter=',')
data = np.loadtxt("/content/drive/MyDrive/Dataset/Obfuscated-MalMem2022 Mod 3.csv", delimiter=',')

# print(data)
X, y = data[:46876, 2:56], data[:46876,57]

y = np.array([int(e) for e in y])
print(y.shape)
y = np.squeeze(y)

#y[y == 1] = 0
#y[y == 2] = 1
#y[y == 3] = 2

Xp= data[46877:,2:56]
#X = X[:46876, 2:56]

yp = data[46877:,57]
#y = y[:46876,57]


# print(npy)
# print(npy.shape)
# y = Y
# establecer el dígito cero en 0, en lugar del 10 asignado a este conjunto de datos
# Esto se hace debido a que el conjunto de datos se utilizó en MATLAB donde no hay índice 0
# m = y.size

print(X.shape)
#print(y.shape)
#print(Xp.shape)
#print(yp.shape)


print(X)
print(y)
print(yp)

(46876,)
(46876, 54)
[[ 45.          17.          10.55555556 ... 121.          87.
    0.5       ]
 [ 38.          15.          10.05263158 ... 118.          87.
    0.        ]
 [ 45.          17.           9.37777778 ... 123.          86.
    0.        ]
 ...
 [ 61.          22.          10.71329694 ... 127.          87.
    0.        ]
 [ 67.          21.          10.43994488 ... 126.          87.
    0.        ]
 [ 47.          18.          11.7872833  ... 124.          87.
    0.        ]]
[1 0 0 ... 1 1 1]
[0. 1. 1. ... 0. 0. 0.]


In [ ]:
# Configurando parametros necesario
input_layer_size  = 54  # Entrada de 13 caracteristicas
hidden_layer_size = 10   # 10 unidades ocultas
num_labels = 2          # 3 etiquetas, de 0 a 2

# carga los pesos en las variables Theta1 y Theta2
# weights = loadmat(os.path.join('/content/gdrive/MyDrive/Colab Notebooks/machine learning/data', 'ex4weights.mat'))
# weights = np.array()
pesos = {}
pesos['Theta1'] = np.random.rand(10, 55)
pesos['Theta2'] = np.random.rand(2, 11)
# print(pesos['Theta1'][:].shape)
# print(pesos['Theta2'][:].shape)

# print(weights['Theta1'][:].shape)
# print(weights['Theta2'][:].shape)

# print(weights['Theta1'][0])
# print(np.roll(weights['Theta1'][0], 1, axis=0))
# Theta1 tiene un tamaño de 25x401
# Theta2 tiene un tamañó de 10x26
# Theta1, Theta2 = weights['Theta1'], weights['Theta2']
Theta1, Theta2 = pesos['Theta1'], pesos['Theta2']
# se intercambia la ultima columa con la primera de Theta2, por cuestiones de indices que utiliza MATLAB
# print(Theta2)
# print(np.roll(Theta2, 1, axis=0))

# Theta2 = np.roll(Theta2, 1, axis=0)

# Desenrollar parámetros
print(Theta1.ravel().shape)
print(Theta2.ravel().shape)

nn_params = np.concatenate([Theta1.ravel(), Theta2.ravel()])
print(nn_params.shape)

(550,)
(22,)
(572,)


In [ ]:
def sigmoid(z):
    """
    Computes the sigmoid of z.
    """
    return 1.0 / (1.0 + np.exp(-z))


def sigmoidGradient(z):

    g = np.zeros(z.shape)

    g = sigmoid(z) * (1 - sigmoid(z))

    return g

In [ ]:
def nnCostFunction(nn_params,
                   input_layer_size,
                   hidden_layer_size,
                   num_labels,
                   X, y, lambda_= 0.0):

    # Reshape nn_params back into the parameters Theta1 and Theta2, the weight matrices
    # for our 2 layer neural network
    Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                        (hidden_layer_size, (input_layer_size + 1)))

    Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                        (num_labels, (hidden_layer_size + 1)))

    m = y.size

    J = 0
    Theta1_grad = np.zeros(Theta1.shape)
    Theta2_grad = np.zeros(Theta2.shape)

    a1 = np.concatenate([np.ones((m, 1)), X], axis=1)

    a2 = sigmoid(a1.dot(Theta1.T))
    a2 = np.concatenate([np.ones((a2.shape[0], 1)), a2], axis=1)

    a3 = sigmoid(a2.dot(Theta2.T))

    # print("-"*20)
    # print(y.shape)
    # print(y.reshape(-1))
    # print("-"*20)
    y_matrix = y.reshape(-1)
    # print(y.shape)
    y_matrix = np.eye(num_labels)[y_matrix]
    # print(y_matrix)

    temp1 = Theta1
    temp2 = Theta2

    # Agregar el termino de regularización

    reg_term = (lambda_ / (2 * m)) * (np.sum(np.square(temp1[:, 1:])) + np.sum(np.square(temp2[:, 1:])))

    J = (-1 / m) * np.sum((np.log(a3) * y_matrix) + np.log(1 - a3) * (1 - y_matrix)) + reg_term

    # Backpropogation

    delta_3 = a3 - y_matrix
    delta_2 = delta_3.dot(Theta2)[:, 1:] * sigmoidGradient(a1.dot(Theta1.T))

    Delta1 = delta_2.T.dot(a1)
    Delta2 = delta_3.T.dot(a2)

    # Agregar regularización al gradiente

    Theta1_grad = (1 / m) * Delta1
    Theta1_grad[:, 1:] = Theta1_grad[:, 1:] + (lambda_ / m) * Theta1[:, 1:]

    Theta2_grad = (1 / m) * Delta2
    Theta2_grad[:, 1:] = Theta2_grad[:, 1:] + (lambda_ / m) * Theta2[:, 1:]

    # ===================== Alterntate solutions =====================
    # my_final_matrix = np.zeros(a3.shape)
    # for c in np.arange(num_labels):
    #    my_final_matrix[:, c] = (np.log(a3[:, c]) * (y == c)) + (np.log(1 - a3[:, c]) * (1 - (y == c)))
    #J = (-1 / m) * np.sum(my_final_matrix)
    # ================================================================

    # ================================================================
    # Unroll gradients
    # grad = np.concatenate([Theta1_grad.ravel(order=order), Theta2_grad.ravel(order=order)])

    grad = np.concatenate([Theta1_grad.ravel(), Theta2_grad.ravel()])

    return J, grad

In [ ]:
lambda_ = 0
J, _ = nnCostFunction(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda_)
print('Costo en parametros (cargado de ex4weights): %.6f ' % J)
print('El costo debe esta cercano a               : 0.287629')

Costo en parametros (cargado de ex4weights): 4.395460 
El costo debe esta cercano a               : 0.287629


In [ ]:
z = np.array([-1, -0.5, 0, 0.5, 1])
g = sigmoidGradient(z)
print('Gradiente sigmoide evaluada con [-1 -0.5 0 0.5 1]:\n  ')
print(g)

Gradiente sigmoide evaluada con [-1 -0.5 0 0.5 1]:
  
[0.19661193 0.23500371 0.25       0.23500371 0.19661193]


In [ ]:
def randInitializeWeights(L_in, L_out, epsilon_init=0.12):
    """
    Randomly initialize the weights of a layer in a neural network.

    Parameters
    ----------
    L_in : int
        Number of incomming connections.

    L_out : int
        Number of outgoing connections.

    epsilon_init : float, optional
        Range of values which the weight can take from a uniform
        distribution.

    Returns
    -------
    W : array_like
        The weight initialiatized to random values.  Note that W should
        be set to a matrix of size(L_out, 1 + L_in) as
        the first column of W handles the "bias" terms."""


    W = np.zeros((L_out, 1 + L_in))
    W = np.random.rand(L_out, 1 + L_in) * 2 * epsilon_init - epsilon_init

    return W

In [ ]:
print('Inicialización de parámetros de redes neuronales...')

initial_Theta1 = randInitializeWeights(input_layer_size, hidden_layer_size)
initial_Theta2 = randInitializeWeights(hidden_layer_size, num_labels)

# Desenrrollr parametros
initial_nn_params = np.concatenate([initial_Theta1.ravel(), initial_Theta2.ravel()], axis=0)

Inicialización de parámetros de redes neuronales...


In [ ]:
#  After you have completed the assignment, change the maxiter to a larger
#  value to see how more training helps.
options= {'maxiter': 1000}

#  You should also try different values of lambda
lambda_ = 1

# Create "short hand" for the cost function to be minimized
costFunction = lambda p: nnCostFunction(p, input_layer_size,
                                        hidden_layer_size,
                                        num_labels, X, y, lambda_)

# Now, costFunction is a function that takes in only one argument
# (the neural network parameters)
res = optimize.minimize(costFunction,
                        initial_nn_params,
                        jac=True,
                        method='TNC',
                        options=options)

# get the solution of the optimization
nn_params = res.x

# Obtain Theta1 and Theta2 back from nn_params
Theta1 = np.reshape(nn_params[:hidden_layer_size * (input_layer_size + 1)],
                    (hidden_layer_size, (input_layer_size + 1)))

Theta2 = np.reshape(nn_params[(hidden_layer_size * (input_layer_size + 1)):],
                    (num_labels, (hidden_layer_size + 1)))

<ipython-input-40-2f5ec00f0be7>:15: OptimizeWarning: Unknown solver options: maxiter
  res = optimize.minimize(costFunction,
<ipython-input-34-fcf1f7fde265>:5: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))


In [ ]:
def predict(Theta1, Theta2, X):
    """
    Predict the label of an input given a trained neural network
    Outputs the predicted label of X given the trained weights of a neural
    network(Theta1, Theta2)
    """
    # Useful values
    m = X.shape[0]
    num_labels = Theta2.shape[0]

    # You need to return the following variables correctly
    p = np.zeros(m)
    h1 = sigmoid(np.dot(np.concatenate([np.ones((m, 1)), X], axis=1), Theta1.T))
    h2 = sigmoid(np.dot(np.concatenate([np.ones((m, 1)), h1], axis=1), Theta2.T))
    p = np.argmax(h2, axis=1)
    return p

In [ ]:
pred = predict(Theta1, Theta2, X[:,:])
print(pred)
print('Training Set Accuracy: %f' % (np.mean(pred == y[:]) * 100))

[1 0 0 ... 1 1 1]
Training Set Accuracy: 100.000000


<ipython-input-34-fcf1f7fde265>:5: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))


In [ ]:
pred = predict(Theta1, Theta2, Xp[:,:])
print(pred)
print('Training Set Accuracy: %f' % (np.mean(pred == yp[:]) * 100))

[0 1 1 ... 0 0 0]
Training Set Accuracy: 100.000000


<ipython-input-34-fcf1f7fde265>:5: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))
